language: node_js
node_js:
  - 8.0.0

before_install:
  - npm install

before_script:
  - "export COVERALLS_SERVICE_NAME=travis-ci"
  - "export COVERALLS_REPO_TOKEN=PtsfxOXNTnovjlROIvVQ7xLi8auoZK7Na"

script:
  - npm test

after_success:
- npm run coveralls
