language: node_js
node_js:
  - 7.0.0

before_install:
  - npm install

before_script:
  - "export COVERALLS_SERVICE_NAME=travis-ci"
  - "export COVERALLS_REPO_TOKEN=7EKJNRr3JCzDyeOZ08KcVMyrIYd90yHPD"

script:
  - npm test

after_success:
- npm run coveralls
