language: node_js
node_js:
  - 9.5.0

before_install:
  - npm install

before_script:
  - "export COVERALLS_SERVICE_NAME=travis-ci"
  - "export COVERALLS_REPO_TOKEN=PtsfxOXNTnovjlROIvVQ7xLi8auoZK7Na"

script:
  - npm run lint
  - npm test

after_success:
  - npm run coveralls
